---
version: 2.1

orbs:
  kitchen: sous-chefs/kitchen@1.0.1

workflows:
  kitchen:
    jobs:
      - kitchen/danger:
          name: danger
          context: Danger
      - kitchen/lint:
          name: lint
      - kitchen/dokken:
          name: server
          suite: server
          requires: [danger, lint]
      - kitchen/dokken-single:
          name: server-verify-no-databag-ubuntu-1604
          suite: server-verify-no-databag
          platform: ubuntu-1604
          requires: [danger, lint]
      - kitchen/dokken-single:
          name: server-verification-ubuntu-1604
          suite: server-verification
          platform: ubuntu-1604
          requires: [danger, lint]
